name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
    - uses: actions/checkout@v3
      with:
        path: "app"
    - run: "npm install"
      working-directory: "app"
    - run: "npm run test -- --coverage --collectCoverageFrom=src/**"
      working-directory: "app"
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
