name: Running Code Coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
   runs-on: ubuntu-latest
   env:
      NODE_ENV: test
   steps:
   
    - uses: actions/checkout@v3
      with:
        path: "app"
        
    - run: "npm install"
      working-directory: "app"
      
    - run: "npm run test -- --coverage"
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
